package labMongoDB;

import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Collections;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.Set;

import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.plaf.ActionMapUIResource;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;

/**
 *
 * @author sebvi
 */
public class FrameCRUD extends javax.swing.JFrame {

	
	DB db;
	DBCollection coleccionPeliculas;
	DBCollection coleccionProductoras;
    /**
     * Creates new form FrameCRUD
     */
    public FrameCRUD() {
		try {

			MongoClient mongoClient = new MongoClient("localhost", 27017);

			DB db = mongoClient.getDB("BasePelis");

			coleccionPeliculas = db.getCollection("Peliculas");
			coleccionProductoras = db.getCollection("Productoras");

			} catch (UnknownHostException ex) {
				System.out.println("Exception al conectar al server de Mongo: " + ex.getMessage());
			}
        initComponents();
        panelPelicula.setVisible(false);
        panelNombrePelicula.setVisible(false);
        botonCancelarPelicula.setVisible(false);
        panelProductora.setVisible(false);
        panelNombreProductora.setVisible(false);
        botonCancelarProductora.setVisible(false);
    }
    
	BasicDBObject dbObjectPelicula = new BasicDBObject();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonRegistrarPelicula = new javax.swing.JButton();
        botonEditarPelicula = new javax.swing.JButton();
        botonEliminarPelicula = new javax.swing.JButton();
        panelPelicula = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombrePelicula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        generoPelicula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        directorPelicula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        franquiciaPelicula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        paisPelicula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        anoPelicula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        duracionPelicula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        productoraPelicula = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        actor1Pelicula = new javax.swing.JTextField();
        actor2Pelicula = new javax.swing.JTextField();
        actor3Pelicula = new javax.swing.JTextField();
        actor4Pelicula = new javax.swing.JTextField();
        botonGuardarPelicula = new javax.swing.JButton();
        botonCancelarPelicula = new javax.swing.JButton();
        panelNombrePelicula = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        peliculaBuscar = new javax.swing.JTextField();
        botonBuscarPelicula = new javax.swing.JButton();
        labelProductora = new javax.swing.JLabel();
        labelPeliculas = new javax.swing.JLabel();
        botonRegistrarProductora = new javax.swing.JButton();
        botonEditarProductora = new javax.swing.JButton();
        botonEliminarProductora = new javax.swing.JButton();
        panelNombreProductora = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        botonBuscarProductora = new javax.swing.JButton();
        panelProductora = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        nombreProductora = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        direccionProductora = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        anoProductora = new javax.swing.JTextField();
        botonGuardarProductora = new javax.swing.JButton();
        botonCancelarProductora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Base de Datos en MongoDB");

        botonRegistrarPelicula.setText("REGISTRAR");
        botonRegistrarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarPeliculaActionPerformed(evt);
            }
        });

        botonEditarPelicula.setText("EDITAR");
        botonEditarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarPeliculaActionPerformed(evt);
            }
        });

        botonEliminarPelicula.setText("ELIMINAR");
        botonEliminarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPeliculaActionPerformed(evt);
            }
        });

        panelPelicula.setToolTipText("");
        panelPelicula.setName(""); // NOI18N

        jLabel2.setText("Nombre");

        jLabel3.setText("Género");

        jLabel4.setText("Director");

        jLabel5.setText("Franquicia");

        jLabel6.setText("País");

        jLabel7.setText("Año");

        jLabel8.setText("Duración");

        jLabel9.setText("Productora");

        jLabel10.setText("Actores");

        botonGuardarPelicula.setBackground(new java.awt.Color(0, 153, 0));
        botonGuardarPelicula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonGuardarPelicula.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarPelicula.setText("GUARDAR");
        botonGuardarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPeliculaActionPerformed(evt);
            }
        });

        botonCancelarPelicula.setBackground(new java.awt.Color(255, 0, 0));
        botonCancelarPelicula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonCancelarPelicula.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelarPelicula.setText("X");
        botonCancelarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPeliculaLayout = new javax.swing.GroupLayout(panelPelicula);
        panelPelicula.setLayout(panelPeliculaLayout);
        panelPeliculaLayout.setHorizontalGroup(
            panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPeliculaLayout.createSequentialGroup()
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(25, 25, 25)
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(anoPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(duracionPelicula))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPeliculaLayout.createSequentialGroup()
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPeliculaLayout.createSequentialGroup()
                                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(actor1Pelicula)
                                    .addComponent(actor2Pelicula)
                                    .addComponent(actor3Pelicula)
                                    .addComponent(actor4Pelicula)
                                    .addComponent(productoraPelicula)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPeliculaLayout.createSequentialGroup()
                                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPeliculaLayout.createSequentialGroup()
                                        .addComponent(paisPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(franquiciaPelicula)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPeliculaLayout.createSequentialGroup()
                                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPeliculaLayout.createSequentialGroup()
                                        .addComponent(generoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(directorPelicula)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPeliculaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(nombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeliculaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonCancelarPelicula))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeliculaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        panelPeliculaLayout.setVerticalGroup(
            panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeliculaLayout.createSequentialGroup()
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPeliculaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPeliculaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addComponent(nombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonCancelarPelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPeliculaLayout.createSequentialGroup()
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(generoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(directorPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(franquiciaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6))
                    .addComponent(paisPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPeliculaLayout.createSequentialGroup()
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(anoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(duracionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(productoraPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(actor1Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actor2Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actor3Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actor4Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(botonGuardarPelicula)
                .addGap(22, 22, 22))
        );

        jLabel11.setText("Nombre de la película");

        botonBuscarPelicula.setText("BUSCAR");
        botonBuscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNombrePeliculaLayout = new javax.swing.GroupLayout(panelNombrePelicula);
        panelNombrePelicula.setLayout(panelNombrePeliculaLayout);
        panelNombrePeliculaLayout.setHorizontalGroup(
            panelNombrePeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombrePeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNombrePeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peliculaBuscar)
                    .addGroup(panelNombrePeliculaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelNombrePeliculaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(botonBuscarPelicula)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNombrePeliculaLayout.setVerticalGroup(
            panelNombrePeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombrePeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peliculaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscarPelicula)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        labelProductora.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelProductora.setForeground(new java.awt.Color(153, 0, 0));
        labelProductora.setText("PRODUCTORAS");

        labelPeliculas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelPeliculas.setForeground(new java.awt.Color(0, 102, 153));
        labelPeliculas.setText("PELÍCULAS");

        botonRegistrarProductora.setText("REGISTRAR");
        botonRegistrarProductora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarProductoraActionPerformed(evt);
            }
        });

        botonEditarProductora.setText("EDITAR");
        botonEditarProductora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarProductoraActionPerformed(evt);
            }
        });

        botonEliminarProductora.setText("ELIMINAR");
        botonEliminarProductora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProductoraActionPerformed(evt);
            }
        });

        jLabel14.setText("Nombre de la productora");

        botonBuscarProductora.setText("BUSCAR");
        botonBuscarProductora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarProductoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNombreProductoraLayout = new javax.swing.GroupLayout(panelNombreProductora);
        panelNombreProductora.setLayout(panelNombreProductoraLayout);
        panelNombreProductoraLayout.setHorizontalGroup(
            panelNombreProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreProductoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNombreProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField14)
                    .addGroup(panelNombreProductoraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelNombreProductoraLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(botonBuscarProductora)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNombreProductoraLayout.setVerticalGroup(
            panelNombreProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreProductoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBuscarProductora)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelProductora.setToolTipText("");
        panelProductora.setName(""); // NOI18N

        jLabel15.setText("Nombre");

        jLabel17.setText("Dirección");

        jLabel20.setText("Año de fundación");

        botonGuardarProductora.setBackground(new java.awt.Color(0, 153, 0));
        botonGuardarProductora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonGuardarProductora.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarProductora.setText("GUARDAR");
        botonGuardarProductora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarProductoraActionPerformed(evt);
            }
        });

        botonCancelarProductora.setBackground(new java.awt.Color(255, 0, 0));
        botonCancelarProductora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonCancelarProductora.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelarProductora.setText("X");
        botonCancelarProductora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarProductoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductoraLayout = new javax.swing.GroupLayout(panelProductora);
        panelProductora.setLayout(panelProductoraLayout);
        panelProductoraLayout.setHorizontalGroup(
            panelProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductoraLayout.createSequentialGroup()
                .addGroup(panelProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelProductoraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductoraLayout.createSequentialGroup()
                                .addComponent(anoProductora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE))
                            .addComponent(direccionProductora)))
                    .addGroup(panelProductoraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nombreProductora, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(botonCancelarProductora))
            .addGroup(panelProductoraLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(botonGuardarProductora, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProductoraLayout.setVerticalGroup(
            panelProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoraLayout.createSequentialGroup()
                .addGroup(panelProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductoraLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel15))
                            .addComponent(nombreProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonCancelarProductora))
                .addGap(14, 14, 14)
                .addGroup(panelProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(anoProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(direccionProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(botonGuardarProductora)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonRegistrarPelicula)
                                    .addComponent(botonEditarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEliminarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(panelNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addComponent(panelPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(panelProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(labelPeliculas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProductora)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonRegistrarProductora)
                                    .addComponent(botonEditarProductora, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEliminarProductora, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(panelNombreProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProductora)
                    .addComponent(labelPeliculas))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botonRegistrarPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEditarPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEliminarPelicula)
                        .addGap(13, 13, 13)
                        .addComponent(panelNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonRegistrarProductora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEditarProductora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEliminarProductora)
                        .addGap(13, 13, 13)
                        .addComponent(panelNombreProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void botonRegistrarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        panelPelicula.setVisible(true);
        botonEditarPelicula.setVisible(false);
        botonEliminarPelicula.setVisible(false);
        botonCancelarPelicula.setVisible(true);
        botonRegistrarProductora.setVisible(false);         
        botonEditarProductora.setVisible(false);
        botonEliminarProductora.setVisible(false);
        labelProductora.setVisible(false);
        
   
        
        //Pelicula peli = new Pelicula(nombrePelicula, generoPelicula, directorPelicula, franquiciaPelicula, paisPelicula, ano, duracionPelicula, productoraPelicula, actor)

        //new Consultas().setVisible(true);
    }                                                      

    private void botonEditarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        panelNombrePelicula.setVisible(true);
        botonRegistrarPelicula.setVisible(false);
        botonEliminarPelicula.setVisible(false);
        botonRegistrarProductora.setVisible(false);
        botonEliminarProductora.setVisible(false);
        botonEditarProductora.setVisible(false); 
    }                                                   

    private void botonEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        panelNombrePelicula.setVisible(true);
    }                                                     

    private void botonCancelarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        panelNombrePelicula.setVisible(false);
        panelPelicula.setVisible(false);
        botonEditarPelicula.setVisible(true);
        botonEliminarPelicula.setVisible(true);
        botonRegistrarProductora.setVisible(true);
        botonEditarProductora.setVisible(true);
        botonEliminarProductora.setVisible(true);
        labelProductora.setVisible(true);
    }                                                     

    private void botonBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        panelPelicula.setVisible(true);
        botonCancelarPelicula.setVisible(true);
        
        //Read
/*        BasicDBObject doc = new BasicDBObject();
        doc.put("nombre", "rocky2");
        if (doc!=null) {
        	DBCursor cursor = coleccionPeliculas.find(doc);
        	while (cursor.hasNext()) {
        		directorPelicula.setText(cursor.next().get("director").toString());
        	}
        } */       
        
        //Delete
        /*DBObject findDoc = new BasicDBObject("nombre", peliculaBuscar.getText());
		coleccionPeliculas.remove(findDoc);*/
        
       // Update 
       /* BasicDBObject doc = new BasicDBObject();
        doc.put("$set", new BasicDBObject().append("nombre", "rocky2"));
        if (doc!=null) {
        	BasicDBObject query1 = new BasicDBObject("nombre", "rocky");
        	coleccionPeliculas.update(query1, doc);
        }    */
        
        // Película en rango de años
        /*DBCursor cursor = coleccionPeliculas.find(new BasicDBObject("ano", new BasicDBObject("$gte", 1995).append("$lte", 2080)));
        while (cursor.hasNext()) {
        System.out.println(cursor.next().get("ano"));
        }*/
        
        // Obtener la duración de las películas, guardarlas, sacar mínima y máxima 
/*        ArrayList<Integer> duracion = new ArrayList<Integer>();
        DBCursor cursor = coleccionPeliculas.find();
        while (cursor.hasNext()) {
        	duracion.add((Integer)cursor.next().get("duracion"));
        }
        System.out.println( "ArrayList Min Value: " + Collections.min(duracion));
        System.out.println( "ArrayList Min Value: " + Collections.max(duracion));
        
        BasicDBObject doc = new BasicDBObject();
        doc.put("duracion", Collections.max(duracion));
        if (doc!=null) {
        	DBCursor cursor2 = coleccionPeliculas.find(doc);
        	while (cursor2.hasNext()) {
        		nombrePelicula.setText(cursor2.next().get("nombre").toString());
        	}
        } */ 
        
        // Cantidad de películas
/*        DBCursor cursorX = coleccionPeliculas.find();
        int cantidad = 0;
        while (cursorX.hasNext()) {
        	System.out.println(cursorX.next().get("nombre"));
        	cantidad++;
        }
        System.out.println(cantidad);*/
        
        // Duración promedio productora
        BasicDBObject doc = new BasicDBObject();
        doc.put("productora", "disney");
        int duracionTotal = 0;
        int duracionPromedio = 0;
        int cantidad = 0;
        if (doc!=null) {
        	DBCursor cursor = coleccionPeliculas.find(doc);
        	while (cursor.hasNext()) {
        		cantidad++;
        		duracionTotal = duracionTotal + (Integer)cursor.next().get("duracion");
        	}
        	System.out.println(cantidad);
        	System.out.println(duracionTotal);
        	if (cantidad!=0) {
        		duracionPromedio = duracionTotal/cantidad;
        	}
        	System.out.println(duracionPromedio);
        } 
       
    }                                                   

    private void botonRegistrarProductoraActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        panelPelicula.setVisible(false);
        botonEditarPelicula.setVisible(false);
        botonEliminarPelicula.setVisible(false);
        botonCancelarPelicula.setVisible(false);
        panelProductora.setVisible(true);
        botonEditarProductora.setVisible(false);
        botonEliminarProductora.setVisible(false);
        botonCancelarProductora.setVisible(true);
        botonRegistrarPelicula.setVisible(false);
    }                                                        

    private void botonEditarProductoraActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        panelNombreProductora.setVisible(true);
    }                                                     

    private void botonEliminarProductoraActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        panelNombreProductora.setVisible(true);
    }                                                       

    private void botonBuscarProductoraActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        panelProductora.setVisible(true);
        botonCancelarProductora.setVisible(true);
    }                                                     

    private void botonCancelarProductoraActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        panelNombreProductora.setVisible(false);
        panelProductora.setVisible(false);
        botonEditarProductora.setVisible(true);
        botonEliminarProductora.setVisible(true);
        botonEditarPelicula.setVisible(true);
        botonEliminarPelicula.setVisible(true);        
    }                                                       

    private void botonGuardarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        BasicDBObject dbObjectPelicula = new BasicDBObject();
        dbObjectPelicula.append("nombre", nombrePelicula.getText());
        dbObjectPelicula.append("genero", generoPelicula.getText());
        dbObjectPelicula.append("director", directorPelicula.getText());
        dbObjectPelicula.append("franquicia", franquiciaPelicula.getText());
        dbObjectPelicula.append("pais", paisPelicula.getText());
        dbObjectPelicula.append("ano", Integer.parseInt(anoPelicula.getText()));
        dbObjectPelicula.append("duracion", Integer.parseInt(duracionPelicula.getText()));
        dbObjectPelicula.append("productora", productoraPelicula.getText());
        dbObjectPelicula.append("actores", actor1Pelicula.getText());
        coleccionPeliculas.insert(dbObjectPelicula);
    }   
    
    private void botonGuardarProductoraActionPerformed(java.awt.event.ActionEvent evt) {                                         
        BasicDBObject dbObjectProductora = new BasicDBObject();
        dbObjectProductora.append("nombre", nombreProductora.getText());
        dbObjectProductora.append("ano", Integer.parseInt(anoProductora.getText()));
        dbObjectProductora.append("direccion", direccionProductora.getText());
        coleccionProductoras.insert(dbObjectProductora);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	    	
        try {
        	

        	
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        
	} 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCRUD().setVisible(true);
            }
        });
        
        
		
    }
    
    public BasicDBObject insertar(DBCollection uno, DBCollection dos) {
		BasicDBObject dBObjectPelicula = new BasicDBObject();

		dBObjectPelicula.append("nombre", nombrePelicula.getText());
		dBObjectPelicula.append("nombre2", generoPelicula.getText());
		
		return dBObjectPelicula;
		
		
    }

    // Variables declaration - do not modify                     
    public static javax.swing.JTextField actor1Pelicula;
    public static javax.swing.JTextField actor2Pelicula;
    public static javax.swing.JTextField actor3Pelicula;
    public static javax.swing.JTextField actor4Pelicula;
    public static javax.swing.JTextField anoPelicula;
    public static javax.swing.JButton botonBuscarPelicula;
    public static javax.swing.JButton botonBuscarProductora;
    public static javax.swing.JButton botonCancelarPelicula;
    public static javax.swing.JButton botonCancelarProductora;
    public static javax.swing.JButton botonEditarPelicula;
    public static javax.swing.JButton botonEditarProductora;
    public static javax.swing.JButton botonEliminarPelicula;
    public static javax.swing.JButton botonEliminarProductora;
    public static javax.swing.JButton botonRegistrarPelicula;
    public static javax.swing.JButton botonRegistrarProductora;
    public static javax.swing.JTextField directorPelicula;
    public static javax.swing.JTextField duracionPelicula;
    public static javax.swing.JTextField franquiciaPelicula;
    public static javax.swing.JTextField generoPelicula;
    public static javax.swing.JButton botonGuardarPelicula;
    public static javax.swing.JButton botonGuardarProductora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jTextField14;
    public static javax.swing.JTextField nombreProductora;
    public static javax.swing.JTextField direccionProductora;
    public static javax.swing.JTextField anoProductora;
    private javax.swing.JLabel labelPeliculas;
    private javax.swing.JLabel labelProductora;
    public static javax.swing.JTextField nombrePelicula;
    public static javax.swing.JTextField paisPelicula;
    private javax.swing.JPanel panelNombrePelicula;
    private javax.swing.JPanel panelNombreProductora;
    public static javax.swing.JPanel panelPelicula;
    private javax.swing.JPanel panelProductora;
    public static javax.swing.JTextField peliculaBuscar;
    public static javax.swing.JTextField productoraPelicula;
    // End of variables declaration                   
}
